version: "3.7"
services:
  monolith:
    # the name of the service                           
    build:
      # tells Docker Compose how to build the image                           
      context: ./monolith
      # tells Docker Compose what directory to look in to build stuff             
      dockerfile: ./Dockerfile.dev
      # tells Docker Compose what Dockerfile to use to build it    
    ports:
      - "8000:8000"
      # list that tells Docker Compose to let us use the port 8000
    volumes:
      - ./monolith:/app
      # list of mappings that we specify wit hthe -v flag in the docker run
    depends_on:
      - rabbitmq
      # this depends on another service which we haven't added yet and monolith should not start until the service has already started

  attendees_microservice:
    build:
      context: ./attendees_microservice
      dockerfile: ./Dockerfile.dev
    ports:
      - "8001:8001"
    volumes:
      - "./attendees_microservice:/app"

  presentation_workflow:
    build:
      context: ./presentation_workflow
      dockerfile: ./Dockerfile.dev
    depends_on:
      - rabbitmq
    volumes:
      - ./presentation_workflow:/app

  rabbitmq:
    image: rabbitmq:3

  mail:
    image: mailhog/mailhog
    environment:
      - MH_SMTP_BIND_ADDR=0.0.0.0:25
    ports:
      - "3000:8025"
