# Generated by Django 4.2.1 on 2023-05-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_rename_picture_url_location_photo_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="photo_url",
            field=models.URLField(default=None, null=True),
        ),
    ]
